### ISSUE TITLE
reflection didn't work while saving the bean

### ISSUE THREAD

**Issue by ruiyu** [jannehietamaki/mungbean#1]
It was weird that reflection didn't work while I saved user bean.
Than I tried to remove "private ObjectId id", and it works.

I modified FieldDefinition class just like this:

```
public class FieldDefinition {
...
public Object get(Object source) {

    try {
        System.out.println(field.toGenericString());
        System.out.println(source.getClass());

        return field.get(source);
    } catch (IllegalArgumentException e) {
        throw new RuntimeException(e);
    } catch (IllegalAccessException e) {
        throw new RuntimeException(e);
    }
}
```

and finally I found this:

public org.bson.types.ObjectId ruiyu.li.mungbean.test.User.id
class org.bson.types.ObjectId

I think that source.getClass() should be "class ruiyu.li.mungbean.test.User"
# 

```
import org.bson.types.ObjectId;

public class User {
    private ObjectId id = new ObjectId();
    private String name;
    private List<Meeting> meetings = new ArrayList<Meeting>();
    ...
}
public class Meeting {
    private ObjectId id = new ObjectId();
    private String title;
    private String content;
    private Date createTime;
    private List<Discussion> discussions = new ArrayList<Discussion>();
    ...
}
public class Discussion {
    private String content;
    private Date createTime;
    private List<Discussion> discussions = new ArrayList<Discussion>();
    ...
}
```
# 

```
@Before
public void create() {
    mungbean = new Mungbean(new Settings(), "localhost", 27017)
            .openDatabase(DB_NAME);
    user = new User("john");
    users = mungbean.openCollection("users", User.class);
}

@Test
public void storeUser() {
    users.save(user);
    User found = users.query(new Query().field("name").is("john"))
    .get(0);
    assertNotNull(found.getId());
    assertEquals(user.getName(), found.getName());
}
```
# 

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set org.bson.types.ObjectId field ruiyu.li.mungbean.test.User.id to org.bson.types.ObjectId
at mungbean.pojo.FieldDefinition.get(FieldDefinition.java:46)
at mungbean.pojo.PojoEncoder.encode(PojoEncoder.java:58)
at mungbean.protocol.bson.BSONCoder.write(BSONCoder.java:52)
at mungbean.protocol.bson.AbstractBSONMap.encode(AbstractBSONMap.java:54)
at mungbean.pojo.PojoEncoder.encode(PojoEncoder.java:60)
at mungbean.protocol.bson.BSONCoder.write(BSONCoder.java:69)
at mungbean.protocol.message.InsertRequest.<init>(InsertRequest.java:19)
at mungbean.AbstractDBCollection$1.doExecuteWithErrorChecking(AbstractDBCollection.java:77)
at mungbean.AbstractDBCollection$ErrorCheckingDBConversation.execute(AbstractDBCollection.java:214)
at mungbean.SingleNodeDbOperationExecutor.execute(SingleNodeDbOperationExecutor.java:53)
at mungbean.SingleNodeDbOperationExecutor.executeWrite(SingleNodeDbOperationExecutor.java:67)
at mungbean.AbstractDBCollection.executeWrite(AbstractDBCollection.java:230)
at mungbean.AbstractDBCollection.save(AbstractDBCollection.java:73)
at ruiyu.li.mungbean.test.PersistenceViaMungbean.storeUser(PersistenceViaMungbean.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.IllegalArgumentException: Can not set org.bson.types.ObjectId field ruiyu.li.mungbean.test.User.id to org.bson.types.ObjectId
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source)
at java.lang.reflect.Field.get(Unknown Source)
at mungbean.pojo.FieldDefinition.get(FieldDefinition.java:44)
... 37 more
```

**Comment by jannehietamaki** [comment]
Your code is using org.bson.types.ObjectId, but Mungbean does not support it yet. You should be using mungbean.ObjectId.

**Comment by ruiyu** [comment]
Thanks a lot!
I had tried mungbean.ObjectId, however, it throwed an exception.
It seems that it can not get my laptop's hardwareAddress.
So I changed to org.bson.types.ObjectId.

BTW, is there any documents for mungbean? I think it is really helpful for us. 

```
java.lang.ArrayIndexOutOfBoundsException: 3
at mungbean.ObjectId.createId(ObjectId.java:52)
at mungbean.ObjectId.<init>(ObjectId.java:40)
at ruiyu.li.mungbean.test.User.<init>(User.java:9)
at ruiyu.li.mungbean.test.PersistenceViaMungbean.create(PersistenceViaMungbean.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by jannehietamaki** [comment]
Ok, fixed the exception that was thrown when hardware address was not available. 

The source code and the tests are the only documentation there is publcly available.
